version: 1.0.{build}
image: Visual Studio 2022
platform:
- x64
configuration:
- Release

install:
  # Install Vulkan SDK
  - ps: |
      $vulkanSdkUrl = "https://sdk.lunarg.com/sdk/download/1.3.268.0/windows/VulkanSDK-1.3.268.0-Installer.exe"
      $vulkanInstaller = "$env:TEMP\VulkanSDK-Installer.exe"
      Invoke-WebRequest -Uri $vulkanSdkUrl -OutFile $vulkanInstaller
      Start-Process -FilePath $vulkanInstaller -ArgumentList "/S" -Wait
      $env:VULKAN_SDK = "C:\VulkanSDK\1.3.268.0"
      $env:PATH = "$env:VULKAN_SDK\Bin;$env:PATH"
      # Verify installation
      if (Test-Path "$env:VULKAN_SDK\Bin\glslangValidator.exe") {
        Write-Host "Vulkan SDK installed successfully"
      } else {
        Write-Error "Vulkan SDK installation failed"
        exit 1
      }

before_build:
- ps: >-
    If ($env:APPVEYOR_BUILD_VERSION -Like "1.0*") {
      $version = src/script/set_git_properties.cmd
      appveyor UpdateBuild -Version $version
    }
- cmd: git submodule update --init --recursive
build:
  project: nxemu.sln
  parallel: true
  verbosity: minimal
after_build:
- src/script/package_zip.cmd %APPVEYOR_BUILD_VERSION%-%platform%.zip %platform%

artifacts:
- path: package/*.zip
